name: SimpleAFK
version: '1.0-SNAPSHOT'
main: org.nikolchev98.simpleafk.SimpleAFK
api-version: '1.20'
commands:
  afk:
    description: Marks a player as AFK
    usage: /<command>
  trigger_afk_messages:
    description: Enables/disables AFK messages
    usage: /<command>
